#!/usr/bin/env bash

# Check required arguments
if [ $# -lt 2 ]; then
    echo "Required input firmware file and output bootloader file to generate:"
    echo "binedit_get_boot firmware.bin boot.bin"
    exit 1
fi

# Extract Bootloader Section from a full FW file
binedit --get --input $1 --output $2 --base_address 0x08000000 --address 0x08000000 --size 32768

exit 0
